# TCP port used by etcd clients. Also resides in
# roles/etcd/defaults/main.yaml
etcd_client_port: 2379
# valid types: package | github-release
flannel_source_type: github-release

# Directory to store downloaded flannel releases
# (in case of using github-releases).
flannel_releases_dir: /opt

#flannel_version
flannel_version: 0.10.0

#The backend that flannel should use
flannel_backend: vxlan

#The default url to download the flannel tar from
flannel_download_url_base: "https://github.com/coreos/flannel/releases/download/v{{ flannel_version }}"
flannel_download_url: "https://github.com/coreos/flannel/releases/download/v0.10.0/flannel-v0.10.0-linux-amd64.tar.gz"

flannel_etcd_use_certs: false
flannel_etcd_certs_dir: "/etc/flanneld/certs"
flannel_etcd_ca_file: "{{ flannel_etcd_certs_dir }}/ca.crt"
flannel_etcd_cert_file: "{{ flannel_etcd_certs_dir }}/client.crt"
flannel_etcd_key_file: "{{ flannel_etcd_certs_dir }}/client.key"

#flannel_options: --etcd-prefix=/coreos.com/network

flannel_system_image: "{{ system_images_registry }}/{{ system_images_registry_namespace }}/flannel:{{ system_images_tag }}"

flannel_options: "--iface=eth0 --etcd-prefix=/cluster.local/network"