---
# This playbook deploys a kubernetes cluster
# with the default addons.

# 网络支持转发
# 拷贝hosts
- name: init hosts
  hosts: all
  user: root
  any_errors_fatal: true
  tasks:
    - name: set sysctl
      sysctl:
        name: '{{ item }}'
        value: 1
        state: present
        reload: true
      with_items:
      - net.ipv4.ip_forward
      - net.bridge.bridge-nf-call-iptables
      - net.bridge.bridge-nf-call-ip6tables
    - name: update_iptables
      shell: iptables -P FORWARD ACCEPT
    - name: copy hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644

- hosts: all
  gather_facts: false
  become: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# Install etcd
- include: deploy-etcd.yml

# Install docker
- include: deploy-docker.yml

# install flannel
- hosts:
    - masters
    - nodes
  become: yes
  roles:
    - { role: etcd-certs, when: flannel_etcd_use_certs|default(false) }
    - { role: flannel, when: networking == 'flannel' }
  tags:
    - network-service-install

# install opencontrail
- hosts: all
  become: yes
  roles:
    - { role: opencontrail, when: networking == 'opencontrail'}
  tags:
    - network-service-install

# install contiv netmaster
- hosts: masters
  become: yes
  roles:
    - { role: contiv, contiv_role: netmaster, when: networking == 'contiv' }

# install kube master services
- include: deploy-master.yml

# launch addons, like dns
- include: deploy-addons.yml

# install kubernetes on the nodes
- include: deploy-node.yml

# provision opencontrail once the services are operational
- hosts:
    - masters[0]
    - nodes
  become: yes
  roles:
    - { role: opencontrail-provision, when: networking == 'opencontrail' }
  tags:
    - network-service-config

# install contiv netplugin
- hosts: nodes
  become: yes
  roles:
    - { role: contiv, contiv_role: netplugin, when: networking == 'contiv' }

# 修改系统配置
- hosts: all
  user: root
  # 是否允许身份切换
  become: yes
  tasks:
  # 支持转发
  - name: update_sysconf
    shell: echo 1 > /proc/sys/net/ipv4/ip_forward
  # 安装必须报
  - name: install_rhsm
    shell: yum install *rhsm* -y
  # 打开防火墙
  #- name: open_firewall
  #  shell: systemctl start firewalld.service

# 为节点添加label
- name: Add label
  hosts: masters
  user: root
  # 是否允许身份切换
  become: yes
  tasks:
  - name: add_label
    shell: kubectl label node node1 role=api-gateway --overwrite
    # shell: kubectl label nodes --all role=api-gateway（所有节点都作为网关）

- name: Pull pause
  hosts: all
  user: root
  # 是否允许身份切换
  become: yes
  tasks:
  - name: pull_pause
    shell: docker pull docker.io/kubernetes/pause
  - name: tag_pause
    shell: docker tag docker.io/kubernetes/pause gcr.io/google_containers/pause-amd64:3.0
