---
- name: MONITORING | Assures {{ kube_config_dir }}/addons/ingress dir exists
  file: path={{ kube_addons_dir }}/ingress state=directory

- name: MONITORING | Install ingress template
  template:
  args:
    src: "ingress/{{ item }}.j2"
    dest: "{{ kube_addons_dir }}/ingress/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - traefix-ingress-ds.yaml
    - traefix-ingress-rbac.yaml
    - traefix-ui-service.yaml
    - kube-system-ingress.yaml