---
- name: MONITORING | Assures {{ kube_config_dir }}/addons/prometheus dir exists
  file: path={{ kube_addons_dir }}/prometheus state=directory

- name: MONITORING | Install prometheus template
  template:
  args:
    src: "prometheus/{{ item }}.j2"
    dest: "{{ kube_addons_dir }}/prometheus/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - prom-configmap.yaml
    - node-exporter.yaml
    - prometheus-deploy.yaml
    - prometheus-svc.yaml
    - pushgateway-rc.yaml
    - pushgateway-svc.yaml
    - rbac-setup.yaml


